# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mercalibre',
                'doc_host': 'https://sanchezgaviermatias.github.io',
                'git_url': 'https://github.com/sanchezgaviermatias/mercalibre',
                'lib_path': 'mercalibre'},
  'syms': {'mercalibre.core': {'mercalibre.core.foo': ('core.html#foo', 'mercalibre/core.py')}}}
